# -*- coding: utf-8 -*-
"""Assignment: Traffic Analysis Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMM6ah2DPz7P4SkSyUYVBuaEWol3qYQv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## **import Data**"""

df=pd.read_csv('/content/traffic.csv')
df

"""## **EDA**"""

df.info()

df.describe()

df.isnull().sum().sum()

from sklearn.preprocessing import LabelEncoder
leabel_encoder =LabelEncoder()

df['Traffic Situation_numeric']=leabel_encoder.fit_transform(df['Traffic Situation'])
#df.drop('Traffic Situation', axis=1, inplace=True)
print(df['Traffic Situation_numeric'].unique())

df['Day of the week_numeric']=leabel_encoder.fit_transform(df['Day of the week'])
#df.drop('Day of the week', axis=1, inplace=True)
print(df['Day of the week_numeric'].unique())

df.dtypes

df.describe()

"""## **visualization**"""

vehicle_columns = ['CarCount', 'BikeCount', 'BusCount', 'TruckCount']
sns.boxplot(data=df[vehicle_columns])
plt.title("Vehicle Count Distribution")
plt.show()

plt.pie(df['Traffic Situation'].value_counts(), labels=df['Traffic Situation'].unique(), autopct='%1.1f%%',colors = [ '#7f63a2', '#8a71b7', '#6a4c93', '#7a9eeb'] ,
       explode = (0,0.1,0,0))
plt.title("Traffic Situation Distribution")
plt.show()

# Calculate the sum of vehicle counts by day of the week
daily_vehicle_counts = df.groupby('Day of the week')[['CarCount', 'BikeCount', 'BusCount', 'TruckCount']].sum()

colors = ['#6a4c93', '#7f63a2', '#8a71b7', '#7a9eeb']
daily_vehicle_counts.plot(kind='bar', figsize=(10, 6), color=colors)
plt.title('Vehicle Count by Day of the Week')
plt.ylabel('Vehicle Count')
plt.xlabel('Day of the Week')
plt.xticks(rotation=45)
plt.show()

# Car Count
plt.figure(figsize=(5, 5))
sns.scatterplot(x='Traffic Situation', y='CarCount', data=df, alpha=0.6, color='purple')
plt.xlabel("Traffic Situation")
plt.ylabel("Car Count")
plt.title("Car Count vs. Traffic Situation (Scatter Plot)")
plt.show()

# Bus Count
plt.figure(figsize=(5, 5))
sns.scatterplot(x='Traffic Situation', y='BusCount', data=df, alpha=0.6, color='purple')
plt.xlabel("Traffic Situation")
plt.ylabel("Bus Count")
plt.title("Bus Count vs. Traffic Situation (Scatter Plot)")
plt.show()

# Truck Count
plt.figure(figsize=(5, 5))
sns.scatterplot(x='Traffic Situation', y='TruckCount', data=df, alpha=0.6, color='purple')
plt.xlabel("Traffic Situation")
plt.ylabel("Truck Count")
plt.title("Truck Count vs. Traffic Situation (Scatter Plot)")
plt.show()

# Bike Count
plt.figure(figsize=(5, 5))
sns.scatterplot(x='Traffic Situation', y='BikeCount', data=df, alpha=0.6, color='purple')
plt.xlabel("Traffic Situation")
plt.ylabel("Bike Count")
plt.title("Bike Count vs. Traffic Situation (Scatter Plot)")
plt.show()

df['Total Vehicle Count'] = df['CarCount'] + df['BikeCount'] + df['BusCount'] + df['TruckCount']
summary = df.groupby('Traffic Situation')['Total Vehicle Count'].sum().reset_index()
summary

"""his suggests that roads experience the most vehicles under normal and heavy traffic, with fewer vehicles during high and low traffic periods."""

df['Time'] = pd.to_datetime(df['Time'])    # Convert the 'Time' column to datetime
df['Hour'] = df['Time'].dt.hour            # Extract the hour
df['Total Vehicle Count'] = df['CarCount'] + df['BikeCount'] + df['BusCount'] + df['TruckCount']
hourly_traffic = df.groupby('Hour')['Total Vehicle Count'].sum().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='Hour', y='Total Vehicle Count', data=hourly_traffic, palette='Purples')
plt.title('Total Traffic Count by Hour of the Day')
plt.xlabel('Hour of the Day')
plt.ylabel('Total Vehicle Count')
plt.xticks(rotation=45)
plt.show()

"""
1. Peak Traffic Hours:
   - Traffic volume is highest around 7 AM - 8 AM and 5 PM - 6 PM.
2. Middle Traffic Periods:
   - Traffic remains relatively high from 6 AM - 9 AM and 3 PM - 7 PM.
3. Lowest Traffic Hours:
   - Traffic is lowest during the late-night and early-morning hours (12 AM - 5 AM).A
The most active hours for traffic happen during morning and evening rush hours, with a significant decrease in traffic during the late night and early morning."""